extends: '@zakodium'
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
  requireConfigFile: false
  babelOptions:
    plugins: ['@babel/plugin-syntax-top-level-await']
rules:
  no-console: off
